version: "3.9"
services:
  backend:
    build: ./backend
    container_name: qrng-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: qrng-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend

